### ISSUE TITLE
Snakecase fields in records should be turned into camelCase

### ISSUE THREAD

**Issue by eeue56** [ahultgren/swagger-elm#17]
Example input:

```
  Banana:
    type: object
    required:
      - banana_id
    properties:
      banana_id:
        type: string
```

right now generates:

```elm
type alias BananaRecord = 
  {  banana_id: String
  }

decodeBanana = ...
  ... 
  |> required "banana_id"
  ...
```

It should instead generate:

```elm
type alias BananaRecord = 
  {  bananaId: String
  }

decodeBanana = ...
  ... 
  |> required "banana_id"
  ...
```

**Comment by ahultgren** [comment]
I think this is a nice-to-have, since `_`, while not idiomatic, works. Also there's the issue of avoiding name collisions. Consider:

```
  Banana:
    type: object
    properties:
      banana_id:
        type: string
      bananaId:
        type: string
```

which would be valid swagger.
